import Head from 'next/head'
import Image from 'next/image'
import '../styles/Home.module.css'
// components
import Header from '../src/components/Header'
import Hero from '../src/components/Hero'
import Brands from '../src/components/Brands'
import About from '../src/components/About'
import Skills from '../src/components/Skills'
import Portfolio from '../src/components/Portfolio'
import Services from '../src/components/Services'
import Testimonials from '../src/components/Testimonials'
import Contact from '../src/components/Contact'
import Footer from '../src/components/Footer'
import BackToTopBtn from '../src/components/BackToTopBtn'

export default function Home() {
  return (
		<div className=''>
			<Head>
				<title>Модель для показа одежды</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div className=''>
				<Header />
				<Hero />
				<Brands />
				<About />
				<Skills />
				<Portfolio />
				<Services />
				<Testimonials />
				<Contact />
				<Footer />
				<BackToTopBtn />
			</div>
		</div>
	)
}
